### ISSUE TITLE
command_line

### ISSUE THREAD

**Issue by matteos1** [caiosweet/Package-Natural-Events#38]
La configurazione della riga di comando binary_sensor utilizzando YAML è stata spostata.

Consulta la documentazione per spostare la tua configurazione YAML nella chiave di integrazione e riavvia Home Assistant per risolvere questo problema.
C'è un command line che dovrebbe essere formattato.
grazie

  - platform: command_line # check URL
    name: download_file # shakemap
    device_class: connectivity
    command: >
      local=$(echo "{{ states('input_text.ingv_path_image') }}" | cut -d" " -f1);
      remote=$(echo "{{ states('input_text.ingv_path_image') }}" | cut -d" " -f2);
      rm -f "$local";
      curl -sSf -Lk -m 5 "$remote" --create-dirs -o "$local" &&
      echo "ON" || echo "OFF"
    scan_interval: 525600 # 1 year
    value_template: "{{ value }}"

**Comment by caiosweet** [comment]
Fixed. Grazie @matteos1
