### ISSUE TITLE
Burze Radius

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Natural-Events#39]
Ciao,

ho appena aggiornato il package all'ultima versione e con la scusa ho modificato anche il radius del sensore burze da 25 a 15.

pkg_natural_events_radius_burze: 15 # Km

Nonostante questo nei messaggi di testo (ricevuti su telegram) continuano a fare riferimento a fulmini caduti nel raggio di 25km.

**Comment by caiosweet** [comment]
Uhmm guarda qui [automazione burze](https://github.com/caiosweet/Package-Natural-Events/blob/main/config/packages/natural_events.yaml#L724)

Ma vedo se posso aggiungere una condizione o trigger differente. 👍🤗

**Comment by jokerigno** [comment]
si ovviamente avendo fatto copia-incolla è identica alla mia. Ma sembra che  {{radius}} resti 25 anche se il valore di pkg_natural_events_radius_burze cambia.

**Comment by caiosweet** [comment]
Ok. Il raggio del componente Burze l'ho impostato a 15 e di fatti arrivano notifiche sotto i 15km. Quello a cui ti riferisci tu è il raggio della zona meteoalert che per impostazione predefinita avevo messo 25km.

**Comment by caiosweet** [comment]
beh si. Ma va aggiornato un bel po' il pacchetto, e semplificato. Inoltre, devo ricordarmi perchè il raggio meteoalert (proprio non ricordo il motivo).
Ah, c'è anche l'automazione per blitzortung. Ma andrebbe gestita bene, perchè i dati sono tanti :D:D
Va beh, nel periodo estivo, con notifiche, si spera, minori, cercherò di dargli una bella sistemata... specialmente i template e le automazioni, magari renderla unica e blueprint

**Comment by caiosweet** [comment]
Ieri sera l'autore di Burze ha realizzato il componente configurabile via UI... quindi dovrò vedere che cosa è cambiato :D
intanto ho aperto una discussione per il package #40
