### ISSUE TITLE
Command Line sensor changed 

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Natural-Events#41]
La configurazione Command Line sensor utilizzando YAML è stata spostata.

Consulta la documentazione per spostare la tua configurazione YAML nella chiave di integrazione e riavvia Home Assistant per risolvere questo problema.

New structure for the sensor is the following:

# Example configuration.yaml entry
command_line:
  - sensor:
      command: SENSOR_COMMAND
  - sensor:
      command: SENSOR_COMMAND_2

**Comment by caiosweet** [comment]
Si, da un po'... Ma mi pare l'ho già inserito.
[Command line](https://github.com/caiosweet/Package-Natural-Events/blob/cdd34ccd1e88334cffc56f8e1a91df4edd0bb904/config/packages/natural_events.yaml#L472)

Resta da aggiustare Burze.
