### ISSUE TITLE
Aggiornamenti

### ISSUE THREAD

**Issue by gio82c** [caiosweet/Package-Natural-Events#42]
Ciao e grazie per l'ottimo lavoro fatto, mi piace molto...mi stavo chiedendo se c'è un modo per avere notifiche quando viene pubblicato un aggiornamento, modifica o miglioria.

**Comment by caiosweet** [comment]
Ciao. Grazie. In realtà, il modo più semplice è quello di usare [l'integrazione per GitHub](https://www.home-assistant.io/integrations/github/#latest-release), magari arrivando solo il sensore della ultima release.

**Comment by gio82c** [comment]
Grazie
